### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [judemont/QuizFlow#4]
Please remember increasing `versionCode` with each release, or your updates won't reach existing installations (Android internally uses this to tell versions apart – so devices will assume already having that version):

    Binary files repo/jdm.apps.quizflow_1.apk and repo/jdm.apps.quizflow_v1.2.0.apk differ

(that's a warning from the updater at the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), where [your app is listed](https://apt.izzysoft.de/packages/jdm.apps.quizflow) – be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to add it next to that lonely PlayStore one on your Readme to point there :smiley:)

The culprit lies [in this line](https://github.com/judemont/QuizFlow/blob/main/pubspec.yaml#L4):

```yaml
version: 1.2.0
```

Syntax for Flutter there is `version: <versionName>[+<versionCode>]`, with the latter defaulting to `1`. So that should now have read

```yaml
version: 1.2.0+2
```

Can you please take care that the next release has it properly increased to "something bigger than 2"? Thanks in advance!

**Comment by judemont** [comment]
Hi @IzzySoft, thanks for the advice. 
I had forgotten to change this version code. I'll do it in the next release, soon.

**Comment by judemont** [comment]
Oh, and I added your izzyondroid badge ! :wink:

**Comment by IzzySoft** [comment]
Thanks a lot! :star_struck:
