### ISSUE TITLE
Bug with flashcards (n probably write)

### ISSUE THREAD

**Issue by douxxu** [judemont/QuizFlow#7]
When we got all the corect answers, the button "Practice words you don't know" is still here, and if we press it, it opens a flashcard window with no flashcards

**Comment by judemont** [comment]
Ok. But. Why do you want to press this button if anyways you know that you have done all words ?

**Comment by douxxu** [comment]
idk, there is still an useless button

**Comment by judemont** [comment]
Not everything is mean to be usefull...

**Comment by douxxu** [comment]
idc remove it

**Comment by judemont** [comment]
no 🥰🥰

**Comment by judemont** [comment]
Sorry

**Comment by judemont** [comment]
Don't take it against you, please

**Comment by judemont** [comment]
Don't take it wront, but my app is only for smart people who don't click on a button "Practice words you dont know" When you know all the words....

**Comment by douxxu** [comment]
💀

**Comment by judemont** [comment]
![image](https://github.com/user-attachments/assets/a09bfde5-0a29-4fb4-b24a-9f9ccf7422fc)
